### PR TITLE
Adding db preferences.

### PR DESCRIPTION
**Pull request by acrosman**
Starting to work on settings for #30.

### CODE REVIEW

**Comment by acrosman** [comment]
Initial preference pane now includes:
image

**Comment by allisonletts** [comment]
Yessss

looking at this, not sure which options can be combined for a valid state. Like, picklist is enum + only unrestricted varchar values? Does that work? If the checkboxes are only valid for one of the radio buttons, either disable the invalid option or put the checkbox element directly under its controlling radio button

**Comment by allisonletts** [comment]
Typo: Make Looksups Char(18)
—change to Lookups

**Comment by acrosman** [comment]
So far, I think, all the combinations will work.  But yes, validations can be added as needed.  Thanks for catching the typo.

**Comment by acrosman** [comment]
Still needs detection of unrestricted lists, default SF values, adding blanks to enum value sets.

**Pull request merged**
